export const DISPLAY_ALERT = "SHOW_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";

//user Register
export const REGISTER_USER_BEGIN = "REGISTER_USER_BEGIN";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";

//user Login
export const LOGIN_USER_BEGIN = "LOGIN_USER_BEGIN";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";

export const SETUP_USER_BEGIN = "LOGIN_USER_BEGIN";
export const SETUP_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const SETUP_USER_ERROR = "LOGIN_USER_ERROR";

//update user
export const UPDATE_USER_BEGIN = "UPDATE_USER_BEGIN";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";

export const HANDLE_CHANGE = "HANDLE_CHANGE";

export const CLEAR_VALUES = "CLEAR_VALUES";

export const CREATE_JOB_BEGIN = "CREATE_JOB_BEGIN";
export const CREATE_JOB_SUCCESS = "CREATE_JOB_SUCCESS";
export const CREATE_JOB_ERROR = "CREATE_JOB_ERROR";

export const GET_JOBS_BEGIN = "GET_JOBS_BEGIN";
export const GET_JOBS_SUCCESS = "GET_JOBS_SUCCESS";
export const GET_JOBS_ERROR = "GET_JOBS_ERROR";

export const SET_EDIT_JOB = "SET_EDIT_JOB";

export const DELETE_JOB_BEGIN = "DELETE_JOB_BEGIN";

export const EDIT_JOB_BEGIN = "EDIT_JOB_BEGIN";
export const EDIT_JOB_SUCCESS = "EDIT_JOB_SUCCESS";
export const EDIT_JOB_ERROR = "EDIT_JOB_ERROR";

export const ACCEPT_JOB_REQ_BEGIN = "ACCEPT_JOB_REQ_BEGIN";
export const ACCEPT_JOB_REQ_SUCCESS = "ACCEPT_JOB_REQ_SUCCESS";
export const ACCEPT_JOB_REQ_ERROR = "ACCEPT_JOB_REQ_ERROR";

export const REJECT_JOB_REQ_BEGIN = "REJECT_JOB_REQ_BEGIN";
export const REJECT_JOB_REQ_SUCCESS = "REJECT_JOB_REQ_SUCCESS";
export const REJECT_JOB_REQ_ERROR = "REJECT_JOB_REQ_ERROR";

//sidebar
export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";

//logout
export const LOGOUT_USER = "LOGOUT_USER";

// mewa Thameerage
export const APPLY_JOB_BEGIN = "APPLY_JOB_BEGIN";
export const APPLY_JOB_SUCCESS = "APPLY_JOB_SUCCESS";
export const APPLY_JOB_ERROR = "APPLY_JOB_ERROR";

//login password reset
export const LOGIN_PASSWORDREST = "LOGIN_PASSWORDREST";
export const LOGIN_PASSWORDREST_COMPLETE = "LOGIN_PASSWORDREST_COMPLETE";
export const LOGIN_PASSWORDREST_ERROR = "LOGIN_PASSWORDREST_ERROR";

export const GET_APPLIED_JOBS_BEGIN = "GET_APPLIED_JOBS_BEGIN";
export const GET_APPLIED_JOBS_SUCCESS = "GET_APPLIED_JOBS_SUCCESS";

export const CLEAR_FILTERS_APPLIED_JOBS = "CLEAR_FILTERS_APPLIED_JOBS";

//new password
export const LOGIN_NEWPASSWORD = "LOGIN_NEWPASSWORD";
export const LOGIN_NEWPASSWORD_COMPLETE = "LOGIN_NEWPASSWORD_COMPLETE";
export const LOGIN_NEWPASSWORD_ERROR = "LOGIN_NEWPASSWORD_ERROR";

/////////////////////////
export const GET_JOBREQUESTS_BEGIN = "GET_JOBREQUESTS_BEGIN";
export const GET_JOBREQUESTS_SUCCESS = "GET_JOBREQUESTS_SUCCESS";

export const CLEAR_REC_FILTERS = "CLEAR_REC_FILTERS";

//recruiter stats
export const SHOW_REC_STATS_BEGIN = "SHOW_REC_STATS_BEGIN";
export const SHOW_REC_STATS_SUCCESS = "SHOW_REC_STATS_SUCCESS";
//job app stats
export const SHOW_JOB_APP_STATS_BEGIN = "SHOW_JOB_APP_STATS_BEGIN";
export const SHOW_JOB_APP_STATS_SUCCESS = "SHOW_JOB_APP_STATS_SUCCESS";

//delete applied jobs

export const DELETE_JOB_APP_BEGIN = "DELETE_JOB_APP_BEGIN";

//update applied jobs
export const SET_EDIT_APP_JOB = "SET_EDIT_APP_JOB";
export const EDIT_JOB_APP_BEGIN = "EDIT_JOB_APP_BEGIN";
export const EDIT_JOB_APP_SUCCESS = "EDIT_JOB_APP_SUCCESS";
export const EDIT_JOB_APP_ERROR = "EDIT_JOB_APP_ERROR";
//admin get all users

export const GET_ALL_USERS_BEGIN = "GET_ALL_USERS_BEGIN";
export const GET_ALL_USERS_SUCCESS = "GET_ALL_USERS_SUCCESS";

//set update user
export const SET_UPDATE_USER = "SET_UPDATE_USER";

//update user admin
export const UPDATE_USER_ADMIN_BEGIN = "UPDATE_USER_ADMIN_BEGIN";
export const UPDATE_USER_ADMIN_SUCCESS = "UPDATE_USER_ADMIN_SUCCESS";
export const UPDATE_USER_ADMIN_ERROR = "UPDATE_USER_ADMIN_ERROR";

//set delete user
export const SET_DELETE_USER = "SET_DELETE_USER";

//delete user
export const DELETE_USER = "DELETE_USER";

//admin stats
export const SHOW_STATS_BEGIN = "SHOW_STATS_BEGIN ";
export const SHOW_STATS_SUCCESS = "SHOW_STATS_SUCCESS";

//admin clear values
export const CLEAR_VALUES_ADMIN = "CLEAR_VALUES_ADMIN";

//admin pagination
export const CHANGE_VLAUES = "CHANGE_VLAUES";

//admin stats pdf
export const GET_ALL_USERS_BEGIN_PDF = "GET_ALL_USERS_BEGIN_PDF";
export const GET_ALL_USERS_SUCCESS_PDF = "GET_ALL_USERS_SUCCESS_PDF";
